<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Проспой список задач'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('fonts/font-awesome-4.6.2/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('js/to-do-list/task/jquery-ui-1.11.4.custom/jquery-ui.min.css'))
                        ->prependStylesheet($this->basePath('css/todo-list/style.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/to-do-list/task/jquery-ui-1.11.4.custom/datepicker-ru.js'))
            ->prependFile($this->basePath('js/to-do-list/task/jquery-ui-1.11.4.custom/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <header>
            <h1 class="text-center">Простой список задач</h1>
        </header>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <footer>
            <div class="container">
                <div style="float: left;">
                    <p>Задание выполнил <br/> <strong>Александр Мищанюк</strong></p>
                </div>
                <div style="float: right;">
                    <i class="fa fa-envelope-o"></i> <strong>map.m@ua.fm</strong><br/>
                    <a href="https://github.com/AleksandrMishchaniuk" title="Мой GitHub" target="blanck" style="margin: 0 10px">
                        <i class="fa fa-github fa-2x" aria-hidden="true"></i>
                    </a>
                    <a href="https://ua.linkedin.com/in/aleksandr-mishchaniuk-19772849" title="Мой LinkedIn" target="blanck" style="margin: 0 10px">
                        <i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
