<script src="js/to-do-list/task/actions.js"></script>
<script src="js/to-do-list/task/list_handlers.js"></script>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <h3>Новая задача</h3>
        <?php
            $form->setAttribute('action', $this->url('todolist', array('controller'=>'task', 'action'=>'add')));
            $form->setAttribute('id', 'task_form');
            echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <label for="text" class="col-md-2 control-label"><?= $form->get('text')->getLabel() ?></label>
            <div class="col-md-10">
                <?php echo $this->formElement($form->get('text')) ?>
            </div>
        </div>
        <div class="form-group">
            <label for="deadline" class="col-md-2 control-label"><?= $form->get('deadline')->getLabel() ?></label>
            <div class="col-md-3">
                <?php echo $this->formElement($form->get('deadline')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <?php echo $this->formElement($form->get('submit')) ?>
            </div>
        </div>
        <?php echo $this->formElement($form->get('status')) ?>
    </div>
</div>

<div class="test_div"></div>
